### ISSUE TITLE
Key error:"img0"

### ISSUE THREAD

**Issue by knight-fzq** [KaiyangZhou/ssdg-benchmark#1]
Dear author,
  When I follow your directions and run the command:bash run_ssdg.sh ssdg_pacs 210 v1, there is a error that Key error:"Img0". So I ran the command print(batch_x) and I found that there was no key called "img0". Only "img" and "img2" in that dict. 
  Here is the shot screen:
![Screenshot from 2021-08-06 13-51-38](https://user-images.githubusercontent.com/54497635/128462667-9f9cc094-7c56-4bec-bdcd-a037bfc64bb7.png)

**Comment by KaiyangZhou** [comment]
Oops, I upaded the underlying source code in Dassl.pytorch by adding [DATALOADER.RETURN_IMG0](https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/config/defaults.py#L97), which decides whether to return un-augmented images, but forgot to update the config files here. See [here](https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/data/data_manager.py#L249) for more details.

I have updated the config files in this repo so the error is fixed. Please pull the latest commit.

**Comment by knight-fzq** [comment]
Thank you!!!
