### ISSUE TITLE
Office_home_Dataset

### ISSUE THREAD

**Issue by knight-fzq** [KaiyangZhou/ssdg-benchmark#2]
Hi, it's me again. Sorry to disturb you. These days, i ran your codes on office_home data set and found problems. I download office_home data set though your link but it could not be used. And i could not fix it. First is the name of documents and then there is no file named "train" in office_home_dg/art/. Waiting for your help!!

**Comment by knight-fzq** [comment]
I think maybe it is because the version of the data set changed. So could i have a copy of data set that you use to run your codes? My email is ziqingfan0331@gmail.com

**Comment by KaiyangZhou** [comment]
you can download the updated dataset from the same google drive link

**Comment by knight-fzq** [comment]
No, i mean the dataset in that link is undated. And new dataset could not be used in your code.

**Comment by knight-fzq** [comment]
I found the problem was not the data set but your code. Maybe you did not release how to split original images into train and val. When i ran, i got this error:
[Errno 2] No such file or directory: '****/datasets/office_home_dg/art/train'

**Comment by KaiyangZhou** [comment]
please pull the latest commit and see if the error persists

**Comment by knight-fzq** [comment]
I pulled the latest commit and failed again. The error is the same.

**Comment by KaiyangZhou** [comment]
would you be able to show the log here?

also the command to reproduce the error

**Comment by knight-fzq** [comment]
1. pull your latest commit.
2. Download dataset zip file named OfficeHomeDataset_10072016.zip, unzip and changed name called office_home_dg. Rename files like Art, Clipart, "Real World"... in office_home_dg to art,clipart,product,real_world..
3. Download decoder and resnet18 weights
4. Download and unzip splits_ssdg_oh.zip and then rename it to splits_ssdg
5. Edit config file to define dataset path
Then i run the comman bash run_ssdg.sh ssdg_officehome 1950 v1
Then the error came:UserWarning: No file found at "****/datasets/office_home_dg/art/train/Alarm_Clock/000018.jpg"
And i find there is no train and val split in art file.

**Comment by KaiyangZhou** [comment]
Follow this https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/DATASETS.md

**Comment by knight-fzq** [comment]
So i need to move images from sub-label file?
Like art/Alarm_Clock/00001.jpg to art/00001.jpg? But in each sub-label file, there is a file called 00001.jpg.

**Comment by KaiyangZhou** [comment]
YOU DID NOT FOLLOW THE INSTRUCTIONS

**Comment by knight-fzq** [comment]
Ahhhhh! Thank you, sorry to disturb you!! I download the wrong dataset.

**Comment by KaiyangZhou** [comment]
good to hear that!
