### ISSUE TITLE
Dataset number doesnot match the original paper

### ISSUE THREAD

**Issue by kevinbro96** [KaiyangZhou/ssdg-benchmark#3]
Hi! I run your code and the data number of PACS is 9990 (6926+806+2048), but the paper (https://arxiv.org/pdf/1710.03077) says PACS has 9991 data.

***** Dataset statistics *****
  Dataset: SSDGPACS                                                                                                                                                                                   Source domains: ['cartoon', 'photo', 'sketch']
  Target domains: ['art_painting']
  #classes: 7
  #train_x: 210
  #train_u: 6,926                                                                                                                                                                                    
  #val: 806
  #test: 2,048

**Comment by kevinbro96** [comment]
What is the problem?

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/ssdg-benchmark/blob/main/datasets/ssdg_pacs.py
